// Toggle LEDs using interrupts generated by channel 0 of Timer_A in up mode.

#include "msp430g2253.h"

#define LED1	BIT3
#define	LED2	BIT4

void main(){
	WDTCTL = WDTPW|WDTHOLD;			// stop watchdog timer
	P2OUT = ~LED1;				// preload LED1 on, LED2 off
	P2DIR = LED1|LED2;			// set LED1, LED2 as output
	TACCR0 = 49999;				// upper limit of count for TAR
	TACCTL0 = CCIE;				// enable interrupts on compare 0
	TACTL = MC_1|ID_3|TASSEL_2|TACLR;	// set up and start Timer_A
						// up to CCR0 mode, divide clock by 8, clock from SMCLK, clear timer.

	__enable_interrupt();			// Enable interrupts
	while(1){
						// loop forever doing nothing, interrupts do the work (MSP430 is in Low Power Mode)
	__low_power_mode_0 ();
	}
}

						// ISR (Interrupt Service Routine) for Timer A channel 0
#pragma vector = TIMERA0_VECTOR
__interrupt void TA0_ISR (void){
	P2OUT ^= LED1|LED2;			// toggle LEDs
}
